// Auto-generated by export_weights.py — do not edit
#pragma once
#include <stdint.h>

// ── Model hyper-parameters ──────────────────────────────
#define MODEL_HIDDEN_DIM   64
#define MODEL_HIDDEN_DIM2  128
#define MODEL_NUM_HEADS    4
#define MODEL_HEAD_DIM     16
#define MODEL_HEAD_DIM2    32
#define MODEL_SEQ_LEN      40

// ── Target normalisation ────────────────────────────────
#define Y_MEAN  87.05476379394531f
#define Y_STD   8.311744689941406f

// ── INT8 weight scales (symmetric, zero_point = 0) ──────
#define SCALE_RED_ENC_CONV0_W                                   4.58825054e-03f
#define SCALE_RED_ENC_CONV1_W                                   2.76958873e-03f
#define SCALE_RED_ENC_CONV2_W                                   2.22393055e-03f
#define SCALE_IR_ENC_CONV0_W                                    1.32560823e-03f
#define SCALE_IR_ENC_CONV1_W                                    4.29620966e-03f
#define SCALE_IR_ENC_CONV2_W                                    1.93672290e-03f
#define SCALE_FILM_FC0_W                                        7.22831534e-03f
#define SCALE_FILM_FC1_W                                        6.48991903e-03f
#define SCALE_R2I_WQ                                            2.25757249e-03f
#define SCALE_R2I_WK                                            2.61102826e-03f
#define SCALE_R2I_WV                                            1.90344057e-03f
#define SCALE_R2I_WO                                            1.60425168e-03f
#define SCALE_R2I_FFN0_W                                        3.30451294e-03f
#define SCALE_R2I_FFN1_W                                        2.68056500e-03f
#define SCALE_I2R_WQ                                            1.87107036e-03f
#define SCALE_I2R_WK                                            2.72497698e-03f
#define SCALE_I2R_WV                                            2.66974000e-03f
#define SCALE_I2R_WO                                            1.50315266e-03f
#define SCALE_I2R_FFN0_W                                        2.12212885e-03f
#define SCALE_I2R_FFN1_W                                        1.50224450e-03f
#define SCALE_TA_WQ                                             1.94651855e-03f
#define SCALE_TA_WK                                             2.15329207e-03f
#define SCALE_TA_WV                                             1.98917720e-03f
#define SCALE_TA_WO                                             1.52753456e-03f
#define SCALE_TA_FFN0_W                                         2.16746749e-03f
#define SCALE_TA_FFN1_W                                         1.64360984e-03f
#define SCALE_POOL_FC0_W                                        1.65217859e-03f
#define SCALE_POOL_FC1_W                                        6.42146682e-04f
#define SCALE_REG_FC0_W                                         1.60332175e-03f
#define SCALE_REG_FC1_W                                         1.68242259e-03f
#define SCALE_REG_FC2_W                                         1.90411636e-03f

// ── Conv encoder output length after padding ────────────
//  Conv1d(k=5, pad=1): T_out = T_in - 2  (loses 2 samples)
//  Conv1d(k=3, pad=1): T_out = T_in       (same)
//  So after 3 conv blocks: T_out = 400 - 2 = 398
#define CONV_OUT_LEN  398

