"""
gen_test_data_header.py
-----------------------
Converts reference.bin (produced by validate_export.py --dump_ref) into
test_data.h — a C header that embeds real PPG windows and their PyTorch-
reference SpO2 values directly in the Arduino sketch.

The sketch replays these windows at startup, prints PASS/FAIL for each one,
then enters the normal live-sensor loop.

Usage:
    python gen_test_data_header.py \\
        --ref reference.bin \\
        --out test_data.h \\
        --seq_len 400 \\
        --max_windows 5 \\
        --tolerance 2.0

Flash cost per window: seq_len * 2 channels * 4 bytes = e.g. 3.2 KB at T=400,
                       0.4 KB at T=50.  5 windows at T=50 = 2 KB total.
"""

import argparse
import struct


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ref",         default="reference.bin",
                        help="Binary file produced by validate_export.py --dump_ref")
    parser.add_argument("--out",         default="test_data.h",
                        help="Output C header path (place in your Arduino project folder)")
    parser.add_argument("--seq_len",     type=int, default=400,
                        help="Window length T — must match MODEL_SEQ_LEN in the sketch")
    parser.add_argument("--max_windows", type=int, default=5,
                        help="Number of test windows to embed (keep small to save flash)")
    parser.add_argument("--tolerance",   type=float, default=2.0,
                        help="PASS/FAIL threshold in SpO2 %% (default 2.0)")
    args = parser.parse_args()

    T = args.seq_len

    # ── Read windows from reference.bin ───────────────────────────────────────
    with open(args.ref, "rb") as f:
        n_total, = struct.unpack("<i", f.read(4))
        n = min(n_total, args.max_windows)
        windows = []
        for _ in range(n):
            red      = list(struct.unpack(f"<{T}f", f.read(T * 4)))
            ir       = list(struct.unpack(f"<{T}f", f.read(T * 4)))
            skintone, = struct.unpack("<f", f.read(4))
            y_ref,    = struct.unpack("<f", f.read(4))
            windows.append((red, ir, skintone, y_ref))

    # ── Emit header ───────────────────────────────────────────────────────────
    def fmtf(v):
        return f"{v:.7e}f"

    def array(name, vals, T):
        body = ", ".join(fmtf(v) for v in vals)
        return f"static const float {name}[{T}] = {{\n    {body}\n}};"

    lines = [
        "// Auto-generated by gen_test_data_header.py — do not edit",
        "// Contains real PPG windows extracted from your training data.",
        "// Expected SpO2 values are PyTorch model outputs (not ground truth).",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define TEST_N_WINDOWS   {n}",
        f"#define TEST_SEQ_LEN     {T}",
        f"#define TEST_TOLERANCE   {args.tolerance}f   // SpO2 %% pass/fail threshold",
        "",
    ]

    # One array per window per channel
    for i, (red, ir, sk, y) in enumerate(windows):
        lines.append(array(f"test_red_{i}", red, T))
        lines.append(array(f"test_ir_{i}",  ir,  T))
        lines.append("")

    # Skintone and expected values as flat arrays
    sk_vals = ", ".join(fmtf(w[2]) for w in windows)
    y_vals  = ", ".join(fmtf(w[3]) for w in windows)
    lines.append(f"static const float test_skintone[{n}] = {{ {sk_vals} }};")
    lines.append(f"static const float test_expected [{n}] = {{ {y_vals}  }};")
    lines.append("")

    # Pointer arrays so the sketch can index by window number
    red_ptrs = ", ".join(f"test_red_{i}" for i in range(n))
    ir_ptrs  = ", ".join(f"test_ir_{i}"  for i in range(n))
    lines.append(f"static const float* const test_red_windows[{n}] = {{ {red_ptrs} }};")
    lines.append(f"static const float* const test_ir_windows [{n}] = {{ {ir_ptrs}  }};")
    lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    flash_kb = n * T * 2 * 4 / 1024
    print(f"Wrote {args.out}")
    print(f"  {n} windows, T={T}, ~{flash_kb:.1f} KB flash for input data")
    print(f"  Pass/fail tolerance: ±{args.tolerance} SpO2 %")
    print(f"  Expected values are PyTorch outputs (not ground-truth SpO2)")


if __name__ == "__main__":
    main()