"""
gen_weight_headers.py
---------------------
Converts the weights/ directory produced by export_weights.py into a single
C header  weights_flash.h  that declares every weight array as:

    static const int8_t  NAME[] PROGMEM = { ... };   // INT8 weights
    static const float   NAME[] PROGMEM = { ... };   // FP32 biases / LN params

PROGMEM is the AVR/Arduino macro that pins data in flash.
On nRF52840 (Cortex-M4) const arrays are already placed in flash by the
linker; PROGMEM is defined as empty but kept for portability.

Also emits  weights_init.h  — a single function  spo2_weights_init()  that
fills a  SpO2ModelWeights  struct (from spo2_model.h) with all the pointers
and scales from meta.h.

Run after export_weights.py:
    python gen_weight_headers.py --weights_dir weights
"""

import argparse
import os
import struct
import numpy as np


def bin_to_c_array_i8(data: bytes, name: str) -> str:
    vals = struct.unpack(f"{len(data)}b", data)
    body = ", ".join(str(v) for v in vals)
    return (
        f"static const int8_t {name}[] = {{\n"
        f"    {body}\n"
        f"}};\n"
    )


def bin_to_c_array_f32(data: bytes, name: str) -> str:
    n = len(data) // 4
    vals = struct.unpack(f"{n}f", data)
    body = ", ".join(f"{v:.8e}f" for v in vals)
    return (
        f"static const float {name}[] = {{\n"
        f"    {body}\n"
        f"}};\n"
    )


def load_meta_scales(meta_path: str) -> dict:
    """Parse #define SCALE_* lines from meta.h into a dict name->float."""
    scales = {}
    with open(meta_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("#define SCALE_"):
                parts = line.split()
                macro = parts[1]           # SCALE_RED_ENC_CONV0_W etc.
                value = parts[2].rstrip("f")
                # Convert macro name back to weight key:
                # SCALE_RED_ENC_CONV0_W -> red_enc_conv0_w
                key = macro[len("SCALE_"):].lower()
                scales[key] = float(value)
    return scales


def main(weights_dir: str):
    meta_path = os.path.join(weights_dir, "meta.h")
    if not os.path.exists(meta_path):
        raise FileNotFoundError(f"meta.h not found in {weights_dir}. Run export_weights.py first.")

    scales = load_meta_scales(meta_path)

    bin_files = sorted(f for f in os.listdir(weights_dir) if f.endswith(".bin"))

    flash_lines = [
        "// Auto-generated by gen_weight_headers.py — do not edit",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// On nRF52840 const globals are already in flash.",
        "// PROGMEM is a no-op here but keeps Arduino sketch compatibility.",
        "#ifndef PROGMEM",
        "#  define PROGMEM",
        "#endif",
        "",
    ]

    # Identify which files are FP32 (bias/LN) vs INT8 (weight matrices)
    # Naming convention from export_weights.py:
    #   *_w.bin  -> INT8 weight matrix
    #   *_b.bin  -> FP32 bias
    #   *ln*.bin -> FP32 layernorm weight/bias

    for fname in bin_files:
        path = os.path.join(weights_dir, fname)
        name = fname[:-4]  # strip .bin
        data = open(path, "rb").read()

        is_fp32 = (name.endswith("_b") or
                   "ln_" in name or
                   name.endswith("_bq") or name.endswith("_bk") or
                   name.endswith("_bv") or name.endswith("_bo") or
                   name.endswith("_norm1_weight") or name.endswith("_norm1_bias") or
                   name.endswith("_norm2_weight") or name.endswith("_norm2_bias") or
                   name.endswith("_ffn0_b") or name.endswith("_ffn1_b"))

        if is_fp32:
            flash_lines.append(bin_to_c_array_f32(data, name))
        else:
            flash_lines.append(bin_to_c_array_i8(data, name))

    out_flash = os.path.join(weights_dir, "weights_flash.h")
    with open(out_flash, "w") as f:
        f.write("\n".join(flash_lines))
    print(f"Wrote {out_flash}")

    # ── weights_init.h ────────────────────────────────────────────────────────
    # This maps every field in SpO2ModelWeights to the arrays and scales above.
    # Edit if you add/remove layers.
    init_lines = [
        "// Auto-generated by gen_weight_headers.py — do not edit",
        "#pragma once",
        '#include "spo2_model.h"',
        '#include "weights/meta.h"',
        '#include "weights/weights_flash.h"',
        "",
        "static inline void spo2_weights_init(SpO2ModelWeights* W) {",
        "    // ── Conv encoders (red) ────────────────────────────────",
        "    W->red_conv0_w = red_enc_conv0_w;",
        "    W->red_conv0_b = red_enc_conv0_b;",
        "    W->red_conv0_s = SCALE_RED_ENC_CONV0_W;",
        "    W->red_conv1_w = red_enc_conv1_w;",
        "    W->red_conv1_b = red_enc_conv1_b;",
        "    W->red_conv1_s = SCALE_RED_ENC_CONV1_W;",
        "    W->red_conv2_w = red_enc_conv2_w;",
        "    W->red_conv2_b = red_enc_conv2_b;",
        "    W->red_conv2_s = SCALE_RED_ENC_CONV2_W;",
        "",
        "    // ── Conv encoders (ir) ─────────────────────────────────",
        "    W->ir_conv0_w = ir_enc_conv0_w;",
        "    W->ir_conv0_b = ir_enc_conv0_b;",
        "    W->ir_conv0_s = SCALE_IR_ENC_CONV0_W;",
        "    W->ir_conv1_w = ir_enc_conv1_w;",
        "    W->ir_conv1_b = ir_enc_conv1_b;",
        "    W->ir_conv1_s = SCALE_IR_ENC_CONV1_W;",
        "    W->ir_conv2_w = ir_enc_conv2_w;",
        "    W->ir_conv2_b = ir_enc_conv2_b;",
        "    W->ir_conv2_s = SCALE_IR_ENC_CONV2_W;",
        "",
        "    // ── SkinFiLM ──────────────────────────────────────────",
        "    W->film_fc0_w = film_fc0_w;",
        "    W->film_fc0_b = film_fc0_b;",
        "    W->film_fc0_s = SCALE_FILM_FC0_W;",
        "    W->film_fc1_w = film_fc1_w;",
        "    W->film_fc1_b = film_fc1_b;",
        "    W->film_fc1_s = SCALE_FILM_FC1_W;",
        "",
        "    // ── red_to_ir cross-attention ──────────────────────────",
        "    W->r2i_Wq = r2i_Wq;  W->r2i_bq = r2i_bq;  W->r2i_sq = SCALE_R2I_WQ;",
        "    W->r2i_Wk = r2i_Wk;  W->r2i_bk = r2i_bk;  W->r2i_sk = SCALE_R2I_WK;",
        "    W->r2i_Wv = r2i_Wv;  W->r2i_bv = r2i_bv;  W->r2i_sv = SCALE_R2I_WV;",
        "    W->r2i_Wo = r2i_Wo;  W->r2i_bo = r2i_bo;  W->r2i_so = SCALE_R2I_WO;",
        "    W->r2i_ffn0_w = r2i_ffn0_w; W->r2i_ffn0_b = r2i_ffn0_b; W->r2i_sf0 = SCALE_R2I_FFN0_W;",
        "    W->r2i_ffn1_w = r2i_ffn1_w; W->r2i_ffn1_b = r2i_ffn1_b; W->r2i_sf1 = SCALE_R2I_FFN1_W;",
        "    W->r2i_norm1_w = r2i_norm1_weight; W->r2i_norm1_b = r2i_norm1_bias;",
        "    W->r2i_norm2_w = r2i_norm2_weight; W->r2i_norm2_b = r2i_norm2_bias;",
        "",
        "    // ── ir_to_red cross-attention ──────────────────────────",
        "    W->i2r_Wq = i2r_Wq;  W->i2r_bq = i2r_bq;  W->i2r_sq = SCALE_I2R_WQ;",
        "    W->i2r_Wk = i2r_Wk;  W->i2r_bk = i2r_bk;  W->i2r_sk = SCALE_I2R_WK;",
        "    W->i2r_Wv = i2r_Wv;  W->i2r_bv = i2r_bv;  W->i2r_sv = SCALE_I2R_WV;",
        "    W->i2r_Wo = i2r_Wo;  W->i2r_bo = i2r_bo;  W->i2r_so = SCALE_I2R_WO;",
        "    W->i2r_ffn0_w = i2r_ffn0_w; W->i2r_ffn0_b = i2r_ffn0_b; W->i2r_sf0 = SCALE_I2R_FFN0_W;",
        "    W->i2r_ffn1_w = i2r_ffn1_w; W->i2r_ffn1_b = i2r_ffn1_b; W->i2r_sf1 = SCALE_I2R_FFN1_W;",
        "    W->i2r_norm1_w = i2r_norm1_weight; W->i2r_norm1_b = i2r_norm1_bias;",
        "    W->i2r_norm2_w = i2r_norm2_weight; W->i2r_norm2_b = i2r_norm2_bias;",
        "",
        "    // ── temporal self-attention ────────────────────────────",
        "    W->ta_Wq = ta_Wq;  W->ta_bq = ta_bq;  W->ta_sq = SCALE_TA_WQ;",
        "    W->ta_Wk = ta_Wk;  W->ta_bk = ta_bk;  W->ta_sk = SCALE_TA_WK;",
        "    W->ta_Wv = ta_Wv;  W->ta_bv = ta_bv;  W->ta_sv = SCALE_TA_WV;",
        "    W->ta_Wo = ta_Wo;  W->ta_bo = ta_bo;  W->ta_so = SCALE_TA_WO;",
        "    W->ta_ffn0_w = ta_ffn0_w; W->ta_ffn0_b = ta_ffn0_b; W->ta_sf0 = SCALE_TA_FFN0_W;",
        "    W->ta_ffn1_w = ta_ffn1_w; W->ta_ffn1_b = ta_ffn1_b; W->ta_sf1 = SCALE_TA_FFN1_W;",
        "    W->ta_norm1_w = ta_norm1_weight; W->ta_norm1_b = ta_norm1_bias;",
        "    W->ta_norm2_w = ta_norm2_weight; W->ta_norm2_b = ta_norm2_bias;",
        "",
        "    // ── attention pooling ──────────────────────────────────",
        "    W->pool_fc0_w = pool_fc0_w; W->pool_fc0_b = pool_fc0_b; W->pool_fc0_s = SCALE_POOL_FC0_W;",
        "    W->pool_fc1_w = pool_fc1_w; W->pool_fc1_b = pool_fc1_b; W->pool_fc1_s = SCALE_POOL_FC1_W;",
        "",
        "    // ── regressor ─────────────────────────────────────────",
        "    W->reg_fc0_w = reg_fc0_w; W->reg_fc0_b = reg_fc0_b; W->reg_fc0_s = SCALE_REG_FC0_W;",
        "    W->reg_fc1_w = reg_fc1_w; W->reg_fc1_b = reg_fc1_b; W->reg_fc1_s = SCALE_REG_FC1_W;",
        "    W->reg_fc2_w = reg_fc2_w; W->reg_fc2_b = reg_fc2_b; W->reg_fc2_s = SCALE_REG_FC2_W;",
        "",
        "    // ── normalisation ─────────────────────────────────────",
        "    W->y_mean = Y_MEAN;",
        "    W->y_std  = Y_STD;",
        "}",
    ]

    out_init = os.path.join(weights_dir, "weights_init.h")
    with open(out_init, "w") as f:
        f.write("\n".join(init_lines) + "\n")
    print(f"Wrote {out_init}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--weights_dir", default="weights")
    args = parser.parse_args()
    main(args.weights_dir)